services:
  sqlite:
    build: .
    container_name: ft_transcendence_sqlite
    volumes:
      - ./data:/data
    environment:
      - DB_PATH=/data/app.db
      - PORT=7000
      - HOST=0.0.0.0
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:7000/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s